### ISSUE TITLE
profiling route

### ISSUE THREAD

**Issue by sjsafranek** [schollz/gofind#5]
returns the following json. "status" can be standard, debug, etc

{
"registered": "2016-03-19T22:02:07.372934175Z",
"status": "standard",
"uptime": 179724.478663151,
"num_cores": 1
}

**Comment by schollz** [comment]
What does "registered" mean? 
And "status"?

**Comment by sjsafranek** [comment]
Registered is the human readable date when the server started. Status is to indicate what the server state is. Gospatial can be put into a "debug" mode (log to file) if a critical error occurs. I'm using "standard" to indicate everything is fine

**Comment by schollz** [comment]
Added https://github.com/schollz/gofind/commit/5f746711369166fca06700b7edb5cd56ca5f4b62 https://github.com/schollz/gofind/commit/5f746711369166fca06700b7edb5cd56ca5f4b62

The route is `/status`
